project:
  type: website
  output-dir: docs
  title: "Intermediate R at USCOTS"

website:
  title: "USCOTS 2025 Intermediate R Workshop"
  description: "USCOTS 2025 Workshop on Teaching Intermediate R"
  site-url: https://github.com/atheobold/uscots-intermediate-r
  repo-url: https://github.com/atheobold/uscots-intermediate-r
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
       - href: index.qmd
         text: Home
       - href: bio.qmd
         text: Presenters
       - text: Tuesday
         menu:
          - href: materials/00-introductions.qmd
            text: "Introductions"
          - href: materials/01-setup-installs.qmd
            text: "Set-up & Installs"
         #- href: materials/02-complex-pipeline.qmd
         #    text: "More Complex Pipelines"
         #- href: materials/03-complex-data.qmd
         #    text: "More Complex Data"
       - text: Wednesday
         menu:
         # - href: materials/04-professional-viz.qmd
         #    text: "Professional Data Visualizations"
          - href: materials/05-quarto-projects-websites.qmd
            text: "Introduction to Quarto Projects and Websites"
          - href: materials/06-quarto-dashboards.qmd
            text: "Quarto Dashboards (Static & Dynamic)"
         # - href: materials/07-shiny.qmd
         #    text: "Introduction to Shiny"
         #  - href: materials/08-packages.qmd
         #    text: "Package-based Teaching"
         #  - href: materials/09-developer.qmd
         #    text: "Thinking Like a Developer"
         
       - text: Activities
         # menu: 
         #  - href: materials/02-activity-quarto-yaml.qmd
         #    text: "Exploring YAML Options in Quarto Docs"
         #  - href: materials/03-activity-styling-quarto-docs.qmd
         #    text: "Embellishing your Quarto doc"
         #  - href: materials/04-activity-quarto-presentations.qmd
         #    text: "Your first (?) Quarto presentation"
         #  - href: materials/05-activity-styling-quarto-presentations.qmd
         #    text: "Embellishing your Quarto presentation"

    right: 
      - icon: github
        href: https://github.com/atheobold/uscots-intermediate-r
      
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Kelly Bodwin, Tyson Barrett & Allison Theobold"
    background: "#D9E3E4"

format:
  html:
    theme: 
      - cosmo
      - style.scss
    toc: true

callout-appearance: simple

execute:
  freeze: auto